// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWRu6zFwncZ6f6Ee_Og3bXEpZFr5FxmAc',
    appId: '1:903639053753:web:355a3c6658353e3df53268',
    messagingSenderId: '903639053753',
    projectId: 'hello-2ac00',
    authDomain: 'hello-2ac00.firebaseapp.com',
    storageBucket: 'hello-2ac00.appspot.com',
    measurementId: 'G-PX39T8WP66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEQKOgo0662RwReUWFpMfCBrFyMaKiaA',
    appId: '1:903639053753:android:878f6e11cdcafb6cf53268',
    messagingSenderId: '903639053753',
    projectId: 'hello-2ac00',
    storageBucket: 'hello-2ac00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYc_PEJkhXszVdsAoBnkZrTYnfddhAWVU',
    appId: '1:903639053753:ios:f882c15902c10faef53268',
    messagingSenderId: '903639053753',
    projectId: 'hello-2ac00',
    storageBucket: 'hello-2ac00.appspot.com',
    iosClientId: '903639053753-vckfahl100aer5luq3vbm8soq1ce60ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYc_PEJkhXszVdsAoBnkZrTYnfddhAWVU',
    appId: '1:903639053753:ios:f0034800520bee1af53268',
    messagingSenderId: '903639053753',
    projectId: 'hello-2ac00',
    storageBucket: 'hello-2ac00.appspot.com',
    iosClientId: '903639053753-1s22psr34fn6b6d14evfgpdgrb2dm19m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
